# Generated by Django 6.0 on 2026-01-03 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Дата')),
                ('total_orders', models.IntegerField(default=0, verbose_name='Всего заказов')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Выручка')),
                ('total_items_sold', models.IntegerField(default=0, verbose_name='Товаров продано')),
                ('new_users', models.IntegerField(default=0, verbose_name='Новых пользователей')),
                ('active_users', models.IntegerField(default=0, verbose_name='Активных пользователей')),
                ('cart_abandonment_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Процент брошенных корзин')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Дневная статистика',
                'verbose_name_plural': 'Дневная статистика',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MasterStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='Начало периода')),
                ('period_end', models.DateField(verbose_name='Конец периода')),
                ('orders_count', models.IntegerField(default=0, verbose_name='Количество заказов')),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Выручка')),
                ('average_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Средний чек')),
                ('top_product', models.CharField(blank=True, max_length=200, verbose_name='Топ изделие')),
                ('top_product_sales', models.IntegerField(default=0, verbose_name='Продажи топ изделия')),
                ('materials_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость материалов')),
                ('materials_used', models.TextField(blank=True, verbose_name='Использованные материалы')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Сгенерировано')),
                ('master', models.ForeignKey(limit_choices_to={'role': 'master'}, on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Статистика мастера',
                'verbose_name_plural': 'Статистика мастеров',
                'unique_together': {('master', 'period_start', 'period_end')},
            },
        ),
    ]
