# Generated by Django 6.0 on 2026-01-03 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название шаблона')),
                ('description', models.TextField(blank=True, verbose_name='Описание шаблона')),
                ('configuration', models.JSONField(default=dict, verbose_name='Конфигурация параметров')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Базовая цена')),
                ('base_production_days', models.IntegerField(default=5, verbose_name='Базовый срок изготовления (дней)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='products.product')),
            ],
            options={
                'verbose_name': 'Шаблон товара',
                'verbose_name_plural': 'Шаблоны товаров',
            },
        ),
        migrations.CreateModel(
            name='CustomOrderSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configuration', models.JSONField(default=dict, verbose_name='Конфигурация')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Итоговая цена')),
                ('production_days', models.IntegerField(verbose_name='Срок изготовления (дней)')),
                ('sketch', models.ImageField(blank=True, null=True, upload_to='custom_orders/sketches/', verbose_name='Эскиз')),
                ('customer_notes', models.TextField(blank=True, verbose_name='Примечания покупателя')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Согласовано')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата согласования')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_specification', to='orders.orderitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_orders', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custom_orders', to='custom_orders.producttemplate')),
            ],
            options={
                'verbose_name': 'Спецификация кастомного заказа',
                'verbose_name_plural': 'Спецификации кастомных заказов',
            },
        ),
    ]
