# Generated by Django 6.0 on 2026-01-16 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название элемента')),
                ('element_type', models.CharField(choices=[('pattern', 'Узор'), ('embroidery', 'Вышивка'), ('print', 'Принт'), ('text', 'Текст'), ('image', 'Изображение')], max_length=20, verbose_name='Тип элемента')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('preview_image', models.ImageField(blank=True, upload_to='design_elements/', verbose_name='Превью')),
                ('svg_path', models.TextField(blank=True, verbose_name='SVG путь')),
                ('price_addition', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Наценка')),
                ('time_addition', models.IntegerField(default=0, verbose_name='Дополнительное время (часов)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Элемент дизайна',
                'verbose_name_plural': 'Элементы дизайна',
            },
        ),
        migrations.AlterModelOptions(
            name='customorderspecification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Спецификация кастомного заказа', 'verbose_name_plural': 'Спецификации кастомных заказов'},
        ),
        migrations.AlterModelOptions(
            name='producttemplate',
            options={'ordering': ['-is_featured', 'name'], 'verbose_name': 'Шаблон товара', 'verbose_name_plural': 'Шаблоны товаров'},
        ),
        migrations.AddField(
            model_name='customorderspecification',
            name='approval_notes',
            field=models.TextField(blank=True, verbose_name='Примечания мастера'),
        ),
        migrations.AddField(
            model_name='customorderspecification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='producttemplate',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Рекомендуемый'),
        ),
        migrations.AddField(
            model_name='producttemplate',
            name='max_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Максимальная цена'),
        ),
        migrations.AddField(
            model_name='producttemplate',
            name='min_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Минимальная цена'),
        ),
        migrations.AddField(
            model_name='producttemplate',
            name='product_type',
            field=models.CharField(choices=[('clothing', 'Одежда'), ('accessory', 'Аксессуар'), ('decor', 'Декор'), ('jewelry', 'Украшение')], default='clothing', max_length=50, verbose_name='Тип изделия'),
        ),
        migrations.AddField(
            model_name='producttemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.CreateModel(
            name='TemplateDesignElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_x', models.IntegerField(default=0, verbose_name='Позиция X')),
                ('position_y', models.IntegerField(default=0, verbose_name='Позиция Y')),
                ('scale', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='Масштаб')),
                ('rotation', models.IntegerField(default=0, verbose_name='Поворот (градусы)')),
                ('is_required', models.BooleanField(default=False, verbose_name='Обязательный')),
                ('design_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='custom_orders.designelement')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_elements', to='custom_orders.producttemplate')),
            ],
            options={
                'verbose_name': 'Элемент дизайна шаблона',
                'verbose_name_plural': 'Элементы дизайна шаблонов',
                'unique_together': {('template', 'design_element')},
            },
        ),
    ]
