# Generated by Django 6.0 on 2026-01-20 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_orders', '0002_designelement_alter_customorderspecification_options_and_more'),
        ('orders', '0004_allow_null_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customorderspecification',
            name='order_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_specification', to='orders.orderitem'),
        ),
    ]
