# Generated by Django 6.0 on 2026-01-03 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('current_quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Текущее количество')),
                ('unit', models.CharField(choices=[('kg', 'Килограмм'), ('g', 'Грамм'), ('m', 'Метр'), ('cm', 'Сантиметр'), ('piece', 'Штука'), ('liter', 'Литр'), ('ml', 'Миллилитр')], max_length=10, verbose_name='Единица измерения')),
                ('min_quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Минимальный запас')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за единицу')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('master', models.ForeignKey(limit_choices_to={'role': 'master'}, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaterialReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Количество')),
                ('status', models.CharField(choices=[('reserved', 'Зарезервирован'), ('consumed', 'Списан'), ('released', 'Освобождён')], default='reserved', max_length=20, verbose_name='Статус')),
                ('reserved_at', models.DateTimeField(auto_now_add=True, verbose_name='Время резервирования')),
                ('consumed_at', models.DateTimeField(blank=True, null=True, verbose_name='Время списания')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='materials.material')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_reservations', to='orders.order')),
            ],
            options={
                'verbose_name': 'Резервирование материала',
                'verbose_name_plural': 'Резервирования материалов',
            },
        ),
        migrations.CreateModel(
            name='MaterialRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumption_rate', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Норма расхода')),
                ('waste_factor', models.DecimalField(decimal_places=2, default=0.1, max_digits=4, verbose_name='Коэффициент отходов')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='materials.material')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_recipes', to='products.product')),
            ],
            options={
                'verbose_name': 'Рецепт материала',
                'verbose_name_plural': 'Рецепты материалов',
                'unique_together': {('product', 'material')},
            },
        ),
    ]
