# Generated by Django 6.0 on 2026-01-13 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='description',
        ),
        migrations.RemoveField(
            model_name='materialrecipe',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='materialreservation',
            name='consumed_at',
        ),
        migrations.RemoveField(
            model_name='materialreservation',
            name='order',
        ),
        migrations.AddField(
            model_name='material',
            name='color',
            field=models.CharField(blank=True, max_length=50, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='material',
            name='supplier',
            field=models.CharField(blank=True, max_length=200, verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='material',
            name='texture',
            field=models.CharField(blank=True, max_length=100, verbose_name='Текстура'),
        ),
        migrations.AddField(
            model_name='materialreservation',
            name='order_id',
            field=models.IntegerField(default=0, verbose_name='ID заказа'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='material',
            name='current_quantity',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Текущее количество'),
        ),
        migrations.AlterField(
            model_name='material',
            name='min_quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Минимальный запас'),
        ),
        migrations.AlterField(
            model_name='material',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена за единицу'),
        ),
        migrations.AlterField(
            model_name='material',
            name='unit',
            field=models.CharField(choices=[('m', 'Метры'), ('cm', 'Сантиметры'), ('g', 'Граммы'), ('kg', 'Килограммы'), ('pcs', 'Штуки'), ('roll', 'Рулоны')], max_length=10, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='materialrecipe',
            name='waste_factor',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=5, verbose_name='Коэффициент отходов'),
        ),
        migrations.AlterField(
            model_name='materialreservation',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='materialreservation',
            name='status',
            field=models.CharField(choices=[('reserved', 'Зарезервировано'), ('consumed', 'Списано'), ('released', 'Освобождено')], default='reserved', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddIndex(
            model_name='materialreservation',
            index=models.Index(fields=['order_id'], name='materials_m_order_i_4db2d1_idx'),
        ),
        migrations.AddIndex(
            model_name='materialreservation',
            index=models.Index(fields=['status'], name='materials_m_status_d82289_idx'),
        ),
    ]
