# Generated by Django 6.0 on 2026-01-18 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_remove_material_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
    ]
