# Generated by Django 6.0 on 2026-01-19 03:55

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_material_is_active'),
        ('orders', '0004_allow_null_user'),
        ('products', '0005_alter_product_materials'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialrecipe',
            options={'ordering': ['material__name'], 'verbose_name': 'Рецепт материала', 'verbose_name_plural': 'Рецепты материалов'},
        ),
        migrations.AlterModelOptions(
            name='materialreservation',
            options={'ordering': ['-reserved_at'], 'verbose_name': 'Резервирование материала', 'verbose_name_plural': 'Резервирования материалов'},
        ),
        migrations.RemoveIndex(
            model_name='materialreservation',
            name='materials_m_order_i_4db2d1_idx',
        ),
        migrations.AddField(
            model_name='material',
            name='last_purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Цена последней закупки (для отслеживания изменений)', max_digits=10, null=True, verbose_name='Последняя цена закупки'),
        ),
        migrations.AddField(
            model_name='material',
            name='notes',
            field=models.TextField(blank=True, help_text='Дополнительная информация о материале', verbose_name='Примечания'),
        ),
        migrations.AddField(
            model_name='material',
            name='supplier_contact',
            field=models.CharField(blank=True, help_text='Телефон, email или сайт поставщика', max_length=300, verbose_name='Контакты поставщика'),
        ),
        migrations.AddField(
            model_name='materialrecipe',
            name='auto_consume',
            field=models.BooleanField(default=True, help_text='Автоматически списывать материал при производстве изделия', verbose_name='Автоматическое списание'),
        ),
        migrations.AddField(
            model_name='materialrecipe',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Примечания'),
        ),
        migrations.AddField(
            model_name='materialreservation',
            name='consumed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время списания'),
        ),
        migrations.AddField(
            model_name='materialreservation',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Примечания'),
        ),
        migrations.AddField(
            model_name='materialreservation',
            name='order_item',
            field=models.ForeignKey(blank=True, help_text='Связь с позицией в заказе (если резервирование для заказа)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_reservations', to='orders.orderitem', verbose_name='Позиция заказа'),
        ),
        migrations.AddField(
            model_name='materialreservation',
            name='released_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время освобождения'),
        ),
        migrations.AlterField(
            model_name='material',
            name='color',
            field=models.CharField(blank=True, help_text='Основной цвет материала', max_length=50, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='material',
            name='current_quantity',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Текущий остаток на складе', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Текущее количество'),
        ),

        migrations.AlterField(
            model_name='material',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Используется ли материал в производстве', verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='material',
            name='master',
            field=models.ForeignKey(limit_choices_to={'role': 'master'}, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to=settings.AUTH_USER_MODEL, verbose_name='Мастер'),
        ),
        migrations.AlterField(
            model_name='material',
            name='min_quantity',
            field=models.DecimalField(decimal_places=3, default=0, help_text='При достижении этого количества будет показано предупреждение', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Минимальный запас'),
        ),
        migrations.AlterField(
            model_name='material',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Цена в рублях за одну единицу измерения', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена за единицу'),
        ),
        migrations.AlterField(
            model_name='material',
            name='supplier',
            field=models.CharField(blank=True, help_text='Название компании-поставщика', max_length=200, verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='material',
            name='texture',
            field=models.CharField(blank=True, help_text='Текстура материала (гладкая, шероховатая и т.д.)', max_length=100, verbose_name='Текстура'),
        ),
        migrations.AlterField(
            model_name='material',
            name='unit',
            field=models.CharField(choices=[('m', 'Метры'), ('cm', 'Сантиметры'), ('g', 'Граммы'), ('kg', 'Килограммы'), ('pcs', 'Штуки'), ('roll', 'Рулоны'), ('ml', 'Милилитры'), ('l', 'Лиры'), ('sheet', 'Листы'), ('pack', 'Упаковки'), ('spool', 'Катушки')], default='pcs', max_length=10, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='materialrecipe',
            name='consumption_rate',
            field=models.DecimalField(decimal_places=3, help_text='Сколько материала требуется для производства одной единицы изделия', max_digits=10, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Норма расхода'),
        ),

        migrations.AlterField(
            model_name='materialrecipe',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='materials.material', verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='materialrecipe',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_recipes', to='products.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='materialrecipe',
            name='waste_factor',
            field=models.DecimalField(decimal_places=2, default=0.1, help_text='Процент отходов при производстве (0.1 = 10%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(1)], verbose_name='Коэффициент отходов'),
        ),

        migrations.AlterField(
            model_name='materialreservation',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='materials.material', verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='materialreservation',
            name='quantity',
            field=models.DecimalField(decimal_places=3, help_text='Зарезервированное количество', max_digits=12, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='materialreservation',
            name='status',
            field=models.CharField(choices=[('reserved', 'Зарезервировано'), ('consumed', 'Списано'), ('released', 'Освобождено'), ('cancelled', 'Отменено')], default='reserved', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['master', 'is_active'], name='materials_m_master__8cb473_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['current_quantity'], name='materials_m_current_c632de_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['name'], name='materials_m_name_f87747_idx'),
        ),
        migrations.AddIndex(
            model_name='materialrecipe',
            index=models.Index(fields=['product', 'material'], name='materials_m_product_2b588f_idx'),
        ),
        migrations.AddIndex(
            model_name='materialreservation',
            index=models.Index(fields=['reserved_at'], name='materials_m_reserve_7f7160_idx'),
        ),
        migrations.AddIndex(
            model_name='materialreservation',
            index=models.Index(fields=['material', 'status'], name='materials_m_materia_7dde02_idx'),
        ),
        migrations.AddIndex(
            model_name='materialreservation',
            index=models.Index(fields=['order_item'], name='materials_m_order_i_9dbdbb_idx'),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('master', 'name', 'color'), name='unique_material_per_master'),
        ),
        migrations.RemoveField(
            model_name='materialreservation',
            name='order_id',
        ),
    ]
