# Generated by Django 6.0 on 2026-01-20 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_alter_materialrecipe_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='materialrecipe',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='materialreservation',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
