# Generated by Django 6.0 on 2026-01-03 23:21

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='default_address',
            field=models.TextField(blank=True, verbose_name='Адрес по умолчанию'),
        ),
        migrations.AddField(
            model_name='user',
            name='default_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='user',
            name='default_postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Почтовый индекс'),
        ),
        migrations.AddField(
            model_name='user',
            name='master_bio',
            field=models.TextField(blank=True, verbose_name='Описание мастера'),
        ),
        migrations.AddField(
            model_name='user',
            name='master_experience_years',
            field=models.IntegerField(default=0, verbose_name='Опыт работы (лет)'),
        ),
        migrations.AddField(
            model_name='user',
            name='master_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='user',
            name='master_specialization',
            field=models.CharField(blank=True, max_length=200, verbose_name='Специализация'),
        ),
        migrations.AddField(
            model_name='user',
            name='newsletter_subscription',
            field=models.BooleanField(default=True, verbose_name='Подписка на рассылку'),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
