# Generated by Django 6.0 on 2026-01-16 11:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderstatushistory',
            options={'ordering': ['changed_at'], 'verbose_name': 'История статуса заказа', 'verbose_name_plural': 'История статусов заказов'},
        ),
        migrations.AddField(
            model_name='order',
            name='customer_notes',
            field=models.TextField(blank=True, verbose_name='Комментарий покупателя'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='custom_configuration',
            field=models.JSONField(blank=True, null=True, verbose_name='Конфигурация кастомного заказа'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='custom_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена кастомного заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(blank=True, choices=[('courier', 'Курьерская доставка'), ('post', 'Почта России'), ('pickup', 'Самовывоз'), ('sdek', 'СДЭК'), ('boxberry', 'Boxberry')], max_length=50, verbose_name='Способ доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('card_online', 'Картой онлайн'), ('sbp', 'СБП (Система быстрых платежей)'), ('cash_on_delivery', 'Наложенный платеж'), ('card_on_delivery', 'Картой при получении')], max_length=50, verbose_name='Способ оплаты'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='orders_orde_order_n_f3ada5_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_orde_status_c6dd84_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'created_at'], name='orders_orde_user_id_37fed6_idx'),
        ),
    ]
