# Generated by Django 6.0 on 2026-01-13 19:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_remove_material_description_and_more'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='base_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Базовая стоимость материалов'),
        ),
        migrations.AddField(
            model_name='product',
            name='can_be_customized',
            field=models.BooleanField(default=False, verbose_name='Можно кастомизировать'),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=50, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='product',
            name='dimensions',
            field=models.CharField(blank=True, max_length=100, verbose_name='Размеры'),
        ),
        migrations.AddField(
            model_name='product',
            name='materials',
            field=models.ManyToManyField(blank=True, related_name='products', through='materials.MaterialRecipe', to='materials.material', verbose_name='Материалы'),
        ),
        migrations.AddField(
            model_name='product',
            name='search_vector',
            field=models.TextField(blank=True, verbose_name='Вектор поиска'),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.TextField(blank=True, help_text='Теги через запятую для улучшения поиска', verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Вес (г)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='difficulty_level',
            field=models.CharField(blank=True, choices=[('beginner', 'Начинающий'), ('intermediate', 'Средний'), ('advanced', 'Продвинутый'), ('expert', 'Эксперт')], max_length=50, verbose_name='Уровень сложности'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['technique'], name='products_pr_techniq_3e10a7_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['difficulty_level'], name='products_pr_difficu_518d78_idx'),
        ),
    ]
