# Generated by Django 6.0 on 2026-01-19 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_material_is_active'),
        ('products', '0004_add_technique_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='materials',
            field=models.ManyToManyField(blank=True, related_name='products', to='materials.material', verbose_name='Материалы'),
        ),
    ]
